var blueMountain = "This extraordinary coffee, famous for its exquisite flavour and strong body, is grown in the majestic Blue Mountain range in Jamaica."
var blueGrove = "This delightful coffee has an aroma that is captivatingly rich and nutty with a faint hint of citrus."
var sumatra = "One of the finest coffees in the world, medium roasted to accentuate its robust character."
var kona = "Grown and processed using traditional Hawaiian methods, then roasted in small batches to maintain peak freshness and flavour."
var antigua = "An outstanding coffee with a rich spicy, and smokey flavour."